# Site Metadata
title: Alasdair J G Gray
description: Connecting the dots in the World's data
affiliation: Heriot Watt University
email: A.J.G.Gray@hw.ac.uk
url: "https://AlasdairGray.github.io/"
google_scholar: https://scholar.google.co.uk/citations?user=3XRqgLcAAAAJ&hl=en
github_link: https://github.com/AlassdairGray
github_username: AlasdairGray
twitter_username: gray_alasdair
permalink: /posts/:categories/:year/:title/

# Processing configuraitons
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Theme 
theme: jekyll-theme-slate

# Plugins
plugins:
  - "jekyll/scholar"
  - "jekyll-paginate-v2"
  - "jekyll-sitemap"

# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Scholar configuration
scholar:
  style: harvard-cite-them-right
  bibliography: '*.bib'
  sort_by: 'year,month'
  order: descending
  bibliography_template: bib